### ISSUE TITLE
install_sources command bug: no implicit conversion of nil into String

### ISSUE THREAD

**Issue by YK-Unit** [Subito-it/PodBuilder#15]
**Log:**

``` shell 
$ pod_builder install_sources
Updating local specs repositories

CocoaPods 1.10.0.rc.1 is available.
To update use: `sudo gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information, see https://blog.cocoapods.org and the CHANGELOG for this version at https://github.com/CocoaPods/CocoaPods/releases/tag/1.10.0.rc.1

Analyzing dependencies
Checking out SnapKit
no implicit conversion of nil into String
/Library/Ruby/Gems/2.6.0/gems/pod-builder-1.9.4/lib/pod_builder/command/install_sources.rb:51:in `system'
	/Library/Ruby/Gems/2.6.0/gems/pod-builder-1.9.4/lib/pod_builder/command/install_sources.rb:51:in `update_repo'
	/Library/Ruby/Gems/2.6.0/gems/pod-builder-1.9.4/lib/pod_builder/command/install_sources.rb:22:in `block in call'
	/Library/Ruby/Gems/2.6.0/gems/pod-builder-1.9.4/lib/pod_builder/command/install_sources.rb:18:in `each'
	/Library/Ruby/Gems/2.6.0/gems/pod-builder-1.9.4/lib/pod_builder/command/install_sources.rb:18:in `call'
	/Library/Ruby/Gems/2.6.0/gems/pod-builder-1.9.4/exe/pod_builder:362:in `block in parse_commandline'
	/Library/Ruby/Gems/2.6.0/gems/pod-builder-1.9.4/exe/pod_builder:361:in `each'
	/Library/Ruby/Gems/2.6.0/gems/pod-builder-1.9.4/exe/pod_builder:361:in `parse_commandline'
	/Library/Ruby/Gems/2.6.0/gems/pod-builder-1.9.4/exe/pod_builder:379:in `<top (required)>'
	/usr/local/bin/pod_builder:23:in `load'
	/usr/local/bin/pod_builder:23:in `<main>'


Command failed!
```

**Env:**

```
$ ruby -v
ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]

$ pod_builder --version
1.9.4
```

**Comment by tcamin** [comment]
Please try the latest beta beta: `gem install pod-builder --pre`
