### ISSUE TITLE
fatal: not a git repository

### ISSUE THREAD

**Issue by pepasibble** [Subito-it/PodBuilder#49]
Running `pod_builder init` in a newly created React Native app fails with the following:

```
$ pod_builder init
fatal: not a git repository (or any of the parent directories): .git


No git repository found in current folder `<redacted>/AwesomeProject/ios`!

/Library/Ruby/Gems/2.6.0/gems/pod-builder-4.2.0/lib/pod_builder/core.rb:220:in `home'
	/Library/Ruby/Gems/2.6.0/gems/pod-builder-4.2.0/lib/pod_builder/configuration.rb:319:in `podbuilder_path'
	/Library/Ruby/Gems/2.6.0/gems/pod-builder-4.2.0/lib/pod_builder/configuration.rb:129:in `load'
	/Library/Ruby/Gems/2.6.0/gems/pod-builder-4.2.0/exe/pod_builder:362:in `parse_commandline'
	/Library/Ruby/Gems/2.6.0/gems/pod-builder-4.2.0/exe/pod_builder:383:in `<top (required)>'
	/usr/local/bin/pod_builder:23:in `load'
	/usr/local/bin/pod_builder:23:in `<main>'


Command failed!
```

**Comment by tcamin** [comment]
For safety, PodBuilder can be run only under an initialized git repository

**Comment by pepasibble** [comment]
Gotcha.  Maybe we can add an explicit error message that this is a requirement / that this failure is expected behavior.
