### ISSUE TITLE
unable to build_all

### ISSUE THREAD

**Issue by harryt04** [Subito-it/PodBuilder#66]
I'm getting the following error when I try to build_all and I have no idea how to proceed. The error message seems generic and unhelpful.

```
Loading Podfile
Adding a custom script phase for Pod RNFBApp: [RNFB] Core Configuration
Adding a custom script phase for Pod RNFBCrashlytics: [RNFB] Crashlytics Configuration
Auto-linking React Native modules for target `xrmobile`: RNBootSplash, RNCAsyncStorage, RNCPicker, RNDeviceInfo, RNFBApp, RNFBCrashlytics, RNGestureHandler, RNLocalize, RNReanimated, RNSVG, RNScreens, RNShare, launchdarkly-react-native-client-sdk, react-native-app-auth, react-native-blob-util, react-native-pdf, react-native-safe-area-context, and react-native-select-contact
Updating local specs repositories
Analyzing dependencies
Fetching podspec for `DoubleConversion` from `../../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`
Fetching podspec for `RCT-Folly` from `../../node_modules/react-native/third-party-podspecs/RCT-Folly.podspec`
Fetching podspec for `boost` from `../../node_modules/react-native/third-party-podspecs/boost.podspec`
Fetching podspec for `glog` from `../../node_modules/react-native/third-party-podspecs/glog.podspec`
Will skip 'FBReactNativeSpec' which defines script_phase in podspec
Checking Podfile.restore
Adding inverse dependencies:
hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint:
hint: 	git config --global init.defaultBranch <name>
hint:
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint:
hint: 	git branch -m <name>
Initialized empty Git repository in /private/tmp/pod_builder/.git/
Preparing build Podfile
Downloading Pods source code
Pod::DSLError
/Users/i24740/.rvm/rubies/ruby-2.7.4/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/podfile.rb:335:in `rescue in block in from_ruby'
	/Users/i24740/.rvm/rubies/ruby-2.7.4/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/podfile.rb:329:in `block in from_ruby'
	/Users/i24740/.rvm/rubies/ruby-2.7.4/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/podfile.rb:50:in `instance_eval'
	/Users/i24740/.rvm/rubies/ruby-2.7.4/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/podfile.rb:50:in `initialize'
	/Users/i24740/.rvm/rubies/ruby-2.7.4/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/podfile.rb:327:in `new'
	/Users/i24740/.rvm/rubies/ruby-2.7.4/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/podfile.rb:327:in `from_ruby'
	/Users/i24740/.rvm/rubies/ruby-2.7.4/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/podfile.rb:293:in `from_file'
	/Users/i24740/.rvm/gems/ruby-2.7.4/gems/cocoapods-1.11.3/lib/cocoapods/config.rb:205:in `podfile'
	/Users/i24740/.rvm/rubies/ruby-2.7.4/lib/ruby/gems/2.7.0/gems/pod-builder-5.0.0/lib/pod_builder/install.rb:281:in `block in download'
	/Users/i24740/.rvm/rubies/ruby-2.7.4/lib/ruby/gems/2.7.0/gems/pod-builder-5.0.0/lib/pod_builder/install.rb:277:in `chdir'
	/Users/i24740/.rvm/rubies/ruby-2.7.4/lib/ruby/gems/2.7.0/gems/pod-builder-5.0.0/lib/pod_builder/install.rb:277:in `download'
	/Users/i24740/.rvm/rubies/ruby-2.7.4/lib/ruby/gems/2.7.0/gems/pod-builder-5.0.0/lib/pod_builder/install.rb:191:in `use_prebuilt_entries_for_unchanged_pods'
	/Users/i24740/.rvm/rubies/ruby-2.7.4/lib/ruby/gems/2.7.0/gems/pod-builder-5.0.0/lib/pod_builder/install.rb:67:in `podfile'
	/Users/i24740/.rvm/rubies/ruby-2.7.4/lib/ruby/gems/2.7.0/gems/pod-builder-5.0.0/lib/pod_builder/command/build.rb:125:in `block in call'
	/Users/i24740/.rvm/rubies/ruby-2.7.4/lib/ruby/gems/2.7.0/gems/pod-builder-5.0.0/lib/pod_builder/command/build.rb:106:in `each'
	/Users/i24740/.rvm/rubies/ruby-2.7.4/lib/ruby/gems/2.7.0/gems/pod-builder-5.0.0/lib/pod_builder/command/build.rb:106:in `call'
	/Users/i24740/.rvm/rubies/ruby-2.7.4/lib/ruby/gems/2.7.0/gems/pod-builder-5.0.0/lib/pod_builder/command/build_all.rb:11:in `call'
	/Users/i24740/.rvm/rubies/ruby-2.7.4/lib/ruby/gems/2.7.0/gems/pod-builder-5.0.0/exe/pod_builder:411:in `block in parse_commandline'
	/Users/i24740/.rvm/rubies/ruby-2.7.4/lib/ruby/gems/2.7.0/gems/pod-builder-5.0.0/exe/pod_builder:410:in `each'
	/Users/i24740/.rvm/rubies/ruby-2.7.4/lib/ruby/gems/2.7.0/gems/pod-builder-5.0.0/exe/pod_builder:410:in `parse_commandline'
	/Users/i24740/.rvm/rubies/ruby-2.7.4/lib/ruby/gems/2.7.0/gems/pod-builder-5.0.0/exe/pod_builder:426:in `<top (required)>'
	/Users/i24740/.rvm/rubies/ruby-2.7.4/bin/pod_builder:23:in `load'
	/Users/i24740/.rvm/rubies/ruby-2.7.4/bin/pod_builder:23:in `<main>'


Command failed!
```

**Comment by tcamin** [comment]
Can you share your Podfile? `Pod::DSLError` generally indicates that the Podfile syntax is wrong
